# Generated by Django 2.0.2 on 2018-02-24 22:38

import articles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(validators=[articles.validators.validate_non_empty_string]),
        ),
    ]
