# Generated by Django 2.0.2 on 2018-02-25 00:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_auto_20180224_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author_id',
            new_name='author',
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('author', 'title')},
        ),
    ]
